<?php

use App\Service;
use App\User;
use Illuminate\Database\Seeder;

class ServicesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // First client (generated by users seeder)
        $client = User::where('role', 0)->first();
        if (! $client) return;

        Service::create([
            'user_id' => $client->id,
            'name' => 'Supervisión'
        ]);
        Service::create([
            'user_id' => $client->id,
            'name' => 'Construcción'
        ]);
        Service::create([
            'user_id' => $client->id,
            'name' => 'Gerencia de proyectos'
        ]);
    }
}
